export default interface iMovie{
  adult: boolean,
  backdrop_path: string,
  budget: number,
  genres:object[],
  homepage: string,
  id: number,
  imdb_id: number,
  original_title: string,
  overview: string,
  popularity: number,
  poster_path: string,
  release_date: Date,
  runtime: number,
  tagline:string,
  title: string,
  vote_avarage:number,
}